# Generated by Django 5.2 on 2025-07-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="blog_photo/",
                verbose_name="Изображение",
            ),
        ),
    ]
